// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_ringct`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ihors-personal-laptop.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// target/release/kohl
// benchmark
// pallet
// --runtime
// target/release/wbuild/kohl-runtime/kohl_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --wasm-execution=compiled
// --pallet
// pallet_ringct
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --template=./scripts/frame-weight-template.hbs
// --output
// pallets/ringct/src/weights_machine.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ringct`.
pub trait WeightInfo {
	fn authorize_transfer() -> Weight;
	fn transfer() -> Weight;
	fn coinbase() -> Weight;
}

/// Weights for `pallet_ringct` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RingCt::KeyImages` (r:1 w:0)
	/// Proof: `RingCt::KeyImages` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `3513`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3513)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `RingCt::KeyImages` (r:1 w:1)
	/// Proof: `RingCt::KeyImages` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::Outputs` (r:16 w:1)
	/// Proof: `RingCt::Outputs` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::BlockFees` (r:1 w:1)
	/// Proof: `RingCt::BlockFees` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::NextOutputIndex` (r:1 w:1)
	/// Proof: `RingCt::NextOutputIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2255`
		//  Estimated: `43934`
		// Minimum execution time: 4_631_000_000 picoseconds.
		Weight::from_parts(4_757_000_000, 43934)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `RingCt::CoinbaseDone` (r:1 w:1)
	/// Proof: `RingCt::CoinbaseDone` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::Emitted` (r:1 w:1)
	/// Proof: `RingCt::Emitted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::BlockFees` (r:1 w:1)
	/// Proof: `RingCt::BlockFees` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::NextOutputIndex` (r:1 w:1)
	/// Proof: `RingCt::NextOutputIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::Outputs` (r:0 w:1)
	/// Proof: `RingCt::Outputs` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
	fn coinbase() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1493`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(64_000_000, 1493)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `RingCt::KeyImages` (r:1 w:0)
	/// Proof: `RingCt::KeyImages` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn authorize_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `97`
		//  Estimated: `3513`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3513)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `RingCt::KeyImages` (r:1 w:1)
	/// Proof: `RingCt::KeyImages` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::Outputs` (r:16 w:1)
	/// Proof: `RingCt::Outputs` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::BlockFees` (r:1 w:1)
	/// Proof: `RingCt::BlockFees` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::NextOutputIndex` (r:1 w:1)
	/// Proof: `RingCt::NextOutputIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2255`
		//  Estimated: `43934`
		// Minimum execution time: 4_631_000_000 picoseconds.
		Weight::from_parts(4_757_000_000, 43934)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `RingCt::CoinbaseDone` (r:1 w:1)
	/// Proof: `RingCt::CoinbaseDone` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::Emitted` (r:1 w:1)
	/// Proof: `RingCt::Emitted` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::BlockFees` (r:1 w:1)
	/// Proof: `RingCt::BlockFees` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::NextOutputIndex` (r:1 w:1)
	/// Proof: `RingCt::NextOutputIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RingCt::Outputs` (r:0 w:1)
	/// Proof: `RingCt::Outputs` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
	fn coinbase() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1493`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(64_000_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
